export const registerConstants = {
    CHECK_MOBILE: 'CHECK_MOBILE',
    MOBILE_USED: 'MOBILE_USED',
    SET_REGISTER_DATA: 'SET_REGISTER_DATA',
    CLEAR_REGISTER_DATA :'CLEAR_REGISTER_DATA',
    REGISTRATION_REQUEST:'REGISTRATION_REQUEST',
    REGISTRATION_SUCCESS:'REGISTRATION_SUCCESS',
    REGISTRATION_FAILURE:'REGISTRATION_FAILURE'
};